### ISSUE TITLE
Any plans to release a pretrained model?

### ISSUE THREAD

**Issue by jaymefosa** [Mirmix/ddlmvs#1]
If you have one available it would help a great deal in evaluating this method. Thank you!

**Comment by Mirmix** [comment]
Unfortunately, I currently don't have the latest models. Most of the experiments were done almost a year ago, so I could not find the model. But for reproducing similar results you need to train the network on DTU dataset for 14 epochs. If I will find the model I will share it with you. But you can also consider using this older version [model](https://drive.google.com/file/d/1ELVvoe6CZUPLLi6PPrXiacF_WGCN5ZiK/view?usp=sharing) which I found. The names of the fielded may be changed, but feel free to give a try.

**Comment by jaymefosa** [comment]
thanks very much! Will try to give this a shot or let it train if 14 epochs is all it needs. Much appreciated!
